version: '3'
services:
   app:
      build:
         context: .
      ports:
         - '4000:4000'
      depends_on:
         - db
      links:
         - db
   db:
      image: postgres
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         PGDATA: /var/lib/postgresql/data/pgdata
      ports:
         - "5432:5432"
      restart: always