version: '3'
services:
   app:
      build:
         context: .
      environment:
         PGUSER: postgres
         PGPASSWORD: postgres
         PGDATABASE: database_name
         PGPORT: 5432
         PGHOST: db
      ports:
         - '4000:4000'
      depends_on:
         - db
   db:
      image: postgres
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         PGDATA: /var/lib/postgresql/data/pgdata
      restart: always